-- Jalankan di Supabase Dashboard > SQL Editor.
-- Membuat akses hanya untuk pengguna yang login dan hanya untuk baris miliknya.
-- Pastikan akun aplikasi sudah masuk melalui Supabase Auth (bukan mode demo lokal).

-- Tambahkan kolom pemilik jika belum ada. Baris lama perlu diisi user_id secara terpisah.
ALTER TABLE public.items
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.items
  ALTER COLUMN user_id SET DEFAULT auth.uid();

ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.items TO authenticated;

DROP POLICY IF EXISTS "ZAVEN users manage own items" ON public.items;
CREATE POLICY "ZAVEN users manage own items"
  ON public.items
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- PERIKSA kebijakan yang sudah ada:
-- Kebijakan permisif lama (misalnya USING (true), atau akses untuk anon/public)
-- dapat tetap mengizinkan akses luas karena kebijakan PERMISSIVE digabung dengan OR.
SELECT policyname, permissive, roles, cmd, qual, with_check
FROM pg_policies
WHERE schemaname = 'public' AND tablename = 'items';

-- Jika sudah ada data barang lama dengan user_id NULL, isi dengan UUID pemiliknya
-- dari Authentication > Users. Contoh (GANTI UUID-nya terlebih dahulu):
-- UPDATE public.items
-- SET user_id = '00000000-0000-0000-0000-000000000000'
-- WHERE user_id IS NULL;

-- Jalankan query ini jika insert masih gagal karena id bernilai NULL.
-- Kirim hasilnya untuk menentukan perbaikan default yang tepat bagi tipe kolom id.
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'items'
ORDER BY ordinal_position;

-- Perbaikan tergantung tipe kolom, jangan jalankan keduanya secara buta:
-- Jika id bertipe bigint/integer dan column_default NULL:
-- ALTER TABLE public.items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- Jika id bertipe uuid dan column_default NULL:
-- ALTER TABLE public.items ALTER COLUMN id SET DEFAULT gen_random_uuid();
-- Jika id bertipe text dan column_default NULL:
-- ALTER TABLE public.items ALTER COLUMN id SET DEFAULT gen_random_uuid()::text;
